# Generated by Django 4.2.27 on 2026-01-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemingredient',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='order.menuitem'),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_usage', to='order.orderitem'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemingredient',
            unique_together={('menu_item', 'inventory')},
        ),
    ]
