# Generated by Django 3.0 on 2025-04-09 22:39

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20250410_0201'),
        ('inventory', '0002_auto_20250325_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryusage',
            name='u_at',
        ),
        # Inside the operations list:
migrations.AddField(
    model_name='table', # Or 'inventory'
    name='c_at',
    # Add default=timezone.now and ensure preserve_default=False
    field=models.DateTimeField(auto_now_add=True, default=timezone.now),
    preserve_default=False,
),
migrations.AddField(
    model_name='table', # Or 'inventory'
    name='u_at',
    # Add default=timezone.now and ensure preserve_default=False
    field=models.DateTimeField(auto_now=True, default=timezone.now),
    preserve_default=False,
),

        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_of_measure',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryusage',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='inventory.Inventory'),
        ),
        migrations.AlterField(
            model_name='inventoryusage',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_usage', to='order.OrderItem'),
        ),
        migrations.AlterField(
            model_name='inventoryusage',
            name='used_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='inventory.Inventory'),
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='order.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemingredient',
            unique_together={('menu_item', 'inventory')},
        ),
    ]
