# Generated by Django 3.0 on 2025-04-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20250410_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='c_at',
        ),
        migrations.RemoveField(
            model_name='table',
            name='u_at',
        ),
    ]
