# Generated by Django 3.0 on 2025-09-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20250602_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='comission',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
