# Generated by Django 3.0 on 2025-09-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_table_comission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='comission',
            new_name='commission',
        ),
    ]
