"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from datetime import timedelta
from decouple import config
import sys
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Detect if running as PyInstaller bundled .exe
RUNNING_AS_EXE = getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS')
if RUNNING_AS_EXE:
    BASE_DIR = sys._MEIPASS


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# Load SECRET_KEY from .env; generate with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = config('SECRET_KEY', default='unsafe-development-key-change-in-production')

# Auto-disable DEBUG in .exe bundle; enable in dev; can override with .env
DEBUG = config('DEBUG', default=(not RUNNING_AS_EXE), cast=bool)

ALLOWED_HOSTS = ["*", "127.0.0.1", "localhost"]



# Django 4.x: Set default auto field for primary keys
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'order',
    'inventory',
    'log',
    'corsheaders',
    'drf_yasg',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Add corsheaders middleware if using it (usually high up)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    ]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
AUTHENTICATION_BACKENDS = [
    'user.backends.PinOnlyAuthBackend',      # Tries PIN login first
    'user.backends.PhonePasswordAuthBackend', # Falls back to phone/password
    # 'django.contrib.auth.backends.ModelBackend', # Remove the default one now
]

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    
]
AUTH_USER_MODEL = 'user.User'
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication', # Use JWT
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # Start with requiring authentication for most actions
        'rest_framework.permissions.IsAuthenticated',
        # Or IsAuthenticatedOrReadOnly if some GET requests should be public
        # 'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    # Optional: Add pagination, filtering, etc.
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 10
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}
SWAGGER_SETTINGS = {
    'tagsSorter': 'alpha',
    'operationsSorter': 'alpha'
}
# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # If you have a top-level static folder
]
CORS_ALLOW_CREDENTIALS = True # If you need cookies/sessions sent across domains
CORS_ALLOW_ALL_ORIGINS = True


# Use normal ESC/POS text size and disable raster rendering to keep receipts small
PRINTER_TEXT_SIZE = config('PRINTER_TEXT_SIZE', default='normal')
# Disable raster by default; enable only if you need fractional scaling
PRINTER_USE_RASTER = config('PRINTER_USE_RASTER', default=False, cast=bool)
PRINTER_SCALE = 1.0
# Raster width (pixels) at the specified DPI for the printable area (80mm paper typical)
PRINTER_RASTER_WIDTH = 576
PRINTER_RASTER_DPI = 203

# Restaurant display name used in receipts
RESTAURANT_NAME = config('RESTAURANT_NAME', default='Akramjon-ustoz')

# Optional shift label shown on receipts
KASSA_SHIFT = config('KASSA_SHIFT', default='')