# Generated by Django 3.0 on 2025-04-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250410_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='PIN Hash'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('waiter', 'Waiter'), ('accountant', 'Accountant'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
    ]
