# Generated by Django 3.0 on 2025-05-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20250429_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('waiter', 'Waiter'), ('accountant', 'Accountant')], default='customer', max_length=50),
        ),
    ]
