# Generated by Django 3.0 on 2025-09-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20250410_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_frequent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=100),
        ),
    ]
