# Generated by Django 3.0 on 2025-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20250918_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subamount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
