# Generated by Django 4.2.27 on 2026-01-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_printer_printjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printjob',
            options={},
        ),
        migrations.RenameField(
            model_name='printjob',
            old_name='created_at',
            new_name='c_at',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='position',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='started_at',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='order.printer'),
        ),
        migrations.AddField(
            model_name='printer',
            name='is_cashier_printer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printer',
            name='port',
            field=models.IntegerField(default=9100),
        ),
        migrations.AddField(
            model_name='printjob',
            name='u_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='payload',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.printer'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('printing', 'Printing'), ('printed', 'Printed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
